<?php

namespace AppBundle\Repository;

/**
 * AddPanRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AddPanRepository extends \Doctrine\ORM\EntityRepository
{
}
